// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2STxjfLNV2D3YJnJGtq4zBL8n0WAM3w',
    appId: '1:179343654407:web:100750d1a68b964caab4a2',
    messagingSenderId: '179343654407',
    projectId: 'richup-f0f05',
    authDomain: 'richup-f0f05.firebaseapp.com',
    databaseURL: 'https://richup-f0f05-default-rtdb.firebaseio.com',
    storageBucket: 'richup-f0f05.firebasestorage.app',
    measurementId: 'G-LM7F3YXJLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhYe9oU868Rp0nb51AKbgjUJaL1rZmzo',
    appId: '1:179343654407:android:34928e0b1a131f52aab4a2',
    messagingSenderId: '179343654407',
    projectId: 'richup-f0f05',
    databaseURL: 'https://richup-f0f05-default-rtdb.firebaseio.com',
    storageBucket: 'richup-f0f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXWwu5e3lzwwYQBmaOiXeBDzfJrBiBkYM',
    appId: '1:179343654407:ios:ee7b716dac7ed983aab4a2',
    messagingSenderId: '179343654407',
    projectId: 'richup-f0f05',
    databaseURL: 'https://richup-f0f05-default-rtdb.firebaseio.com',
    storageBucket: 'richup-f0f05.firebasestorage.app',
    iosClientId: '179343654407-nr1ka72hqgrpevf4uquofgsast1nris7.apps.googleusercontent.com',
    iosBundleId: 'com.example.richUp',
  );

}